# This file generates the GitHub Actions matrix.

board:
  - nice_nano_v2
  - seeeduino_xiao_ble

shield:
  - charybdis_left
  - charybdis_right
  - charybdis_dongle
  - charybdis_dongle prospector_adapter
  - settings_reset

format:
  - bt
  - dongle
  - prospector
  - reset

keymap:
  - qwerty

include:
  - board: nice_nano_v2
    shield: charybdis_right
    keymap: qwerty
    snippet: studio-rpc-usb-uart
